#pragma once

enum ParserExceptionEnum {
	PROCEDURE_EXCEPTION = 1,
	UNIDENTIFIED_EXCEPTION = 2,
	EMPTY_EXCEPTION = 3,
	PRINT_EXCEPTION = 4,
	READ_EXCEPTION = 5,
	ASSIGN_EXCEPTION = 6,
	CALL_EXCEPTION = 7,
	IF_EXCEPTION = 8,
	WHILE_EXCEPTION = 9,
	CONDITIONAL_EXPRESSION_EXCEPTION = 10,
	STANDARD_EXPRESSION_EXCEPTION = 11,
	CHILD_STATEMENT_EXCEPTION = 12,
	READER_EXCEPTION = 13
};
